# Generated by Django 4.1.3 on 2022-11-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
