# Generated by Django 4.1.3 on 2022-11-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_student',
            new_name='is_employee',
        ),
    ]
